airbnb:
  outputs:
    dev:
      type: snowflake
      account: qvpytiz-pp87644
      user: dbt

      role: TRANSFORM
      private_key: "***************************************************************************************************"
      private_key_passphrase: q

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
