models:
  - name: dim_listing_cleansed
    description: "This table contains the cleansed and transformed data for Airbnb listings. It includes key attributes such as listing ID, host ID, room type, and minimum nights. The data is cleansed to ensure accuracy and consistency, making it suitable for analysis and reporting."
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
    columns:
      - name: listing_id
        description: "Unique identifier for each Airbnb listing."
        data_tests:
          - unique
          - not_null
      - name: host_id
        description: "Unique identifier for each host."
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: "Type of room offered in the listing."
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt',
                        'Private room',
                        'Shared room',
                        'Hotel room']
      - name: minimum_nights
        description: '{{doc("dim_listing_cleansed_minimum_nights")}}'
        data_type: integer
        data_tests:
          - positive_values
    
  - name: dim_listings_with_hosts
    data_tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: source('airbnb','listings')
    columns:
      - name: price
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              arguments:
                quantile: 0.99
                min_value: 50
                max_value: 500   
          - dbt_expectations.expect_column_max_to_be_between:
              arguments:
                max_value: 9000
                config:
                  severity: warn

  - name: dim_hosts_cleansed
    description: Cleansed table for the Airbnb hosts
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        data_tests:
          - not_null
          - unique
      
      - name: host_name
        description: The name of the host
        data_tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        data_tests: 
          - accepted_values:
              arguments:
                values: ['t', 'f']